parameters:
    atlassian_connect_license_listener_class: AtlassianConnectBundle\Listener\LicenseListener
    atlassian_connect_jwt_user_provider_class: AtlassianConnectBundle\Security\JWTUserProvider
    atlassian_connect_jwt_authenticator_class: AtlassianConnectBundle\Security\JWTAuthenticator
    atlassian_connect_tenant_entity_class: AtlassianConnectBundle\Entity\Tenant

services:
    kernel.listener.license_listener:
        class: "%atlassian_connect_license_listener_class%"
        arguments: ['@router', '@kernel', '@security.token_storage']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    jwt_user_provider:
        class: "%atlassian_connect_jwt_user_provider_class%"
        arguments: ['@doctrine.orm.entity_manager','%atlassian_connect_token_lifetime%',"%atlassian_connect_tenant_entity_class%"]

    jwt_authenticator:
        class: "%atlassian_connect_jwt_authenticator_class%"
        arguments: ['@jwt_user_provider', '@kernel', '@doctrine.orm.entity_manager', "%atlassian_connect_tenant_entity_class%", "%atlassian_connect_dev_tenant%"]