atlassian_connect_descriptor:
    path: /atlassian-connect.json
    defaults:
        _controller: AtlassianConnectBundle\Controller\DescriptorController::indexaction

atlassian_connect_handshake:
    path: /handshake
    defaults:
        _controller: AtlassianConnectBundle\Controller\HandshakeController::registerAction

atlassian_connect_unlicensed:
    path: /protected/unlicensed
    defaults:
        _controller: AtlassianConnectBundle\Controller\UnlicensedController::unlicensedAction
