parameters:
    atlassian_connect_license_listener_class: AtlassianConnectBundle\Listener\LicenseListener
    atlassian_connect_jwt_user_provider_class: AtlassianConnectBundle\Security\JWTUserProvider
    atlassian_connect_jwt_authenticator_class: AtlassianConnectBundle\Security\JWTAuthenticator
    atlassian_connect_tenant_entity_class: AtlassianConnectBundle\Entity\Tenant

services:
    _defaults:
        public: true
        autowire: false
        autoconfigure: true

    AtlassianConnectBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']


    AtlassianConnectBundle\Controller\UnlicensedController:
        arguments:
            $twig: '@twig'

    AtlassianConnectBundle\Controller\HandshakeController:
        arguments:
            $em: '@Doctrine\Common\Persistence\ObjectManager'
            $logger: '@Psr\Log\LoggerInterface'
            $tenantClass: '%atlassian_connect_tenant_entity_class%'

    AtlassianConnectBundle\Controller\DescriptorController:
        arguments:
            $env: '%kernel.environment%'
            $config: '%atlassian_connect%'

    AtlassianConnectBundle\Command\RequestAPICommand:
        public: false
        arguments:
            $registry: '@Doctrine\Common\Persistence\ManagerRegistry'
            $tenantClass: '%atlassian_connect_tenant_entity_class%'

    AtlassianConnectBundle\Service\AtlassianRestClient:
        arguments:
            $tenant: null
            $tokenStorage: '@Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface'

    kernel.listener.license_listener:
        class: '%atlassian_connect_license_listener_class%'
        arguments:
            $router: '@Symfony\Component\Routing\RouterInterface'
            $kernel: '@Symfony\Component\HttpKernel\KernelInterface'
            $tokenStorage: '@Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    jwt_user_provider:
        class: '%atlassian_connect_jwt_user_provider_class%'
        arguments:
            $registry: '@Doctrine\Common\Persistence\ManagerRegistry'
            $tenantClass: '%atlassian_connect_tenant_entity_class%'

    jwt_authenticator:
        class: "%atlassian_connect_jwt_authenticator_class%"
        arguments:
            $userProvider: '@jwt_user_provider'
            $kernel: '@Symfony\Component\HttpKernel\KernelInterface'
            $registry: '@Doctrine\Common\Persistence\ManagerRegistry'
            $tenantEntityClass: '%atlassian_connect_tenant_entity_class%'
            $devTenant: '%atlassian_connect_dev_tenant%'
